### ISSUE TITLE
segfault when asking to show the trace

### ISSUE THREAD

**Issue by xapantu** [SRI-CSL/sally#31]
Happens with the file attached. It is supposed to be invalid, the ic3 engine correctly says so, but crashes when asking for the trace (without --show-trace it works fine).
[out.mcmt.txt](https://github.com/SRI-CSL/sally/files/210629/out.mcmt.txt)

**Comment by xapantu** [comment]
(gdb) r
Starting program: /home/lucas/sally/build/src/sally out.mcmt --engine ic3 --show-trace
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
invalid
(trace 
  (state

Program received signal SIGSEGV, Segmentation fault.
sally::expr::model::ref::operator-> (this=this@entry=0x7aa650) at /home/lucas/sally/src/expr/model.cpp:480
480	  return d_model->get_model();
(gdb) bt
#0  sally::expr::model::ref::operator-> (this=this@entry=0x7aa650) at /home/lucas/sally/src/expr/model.cpp:480
#1  0x00000000004da9ef in sally::system::state_trace::to_stream (this=0x7aa5a0, out=...) at /home/lucas/sally/src/system/state_trace.cpp:174
#2  0x00000000004db05f in sally::system::operator<< (out=..., trace=...) at /home/lucas/sally/src/system/state_trace.cpp:213
#3  0x00000000004a9431 in sally::parser::query_command::run (this=<optimized out>, ctx=0x7fffffffe420, e=0x7976d0) at /home/lucas/sally/src/parser/command.cpp:137
#4  0x0000000000480810 in main (argc=<optimized out>, argv=<optimized out>) at /home/lucas/sally/src/sally.cpp:131
